tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              display: Title
          -
            handle: logo
            field:
              max_files: 1
              container: assets
              type: assets
              display: Logo
          -
            handle: banners
            field:
              mode: grid
              container: assets
              type: assets
              display: Banners
          -
            handle: default_pokemon_image
            field:
              max_files: 1
              container: assets
              type: assets
              display: 'Default Pokemon Image'
              instructions: 'The image to be used when a Pokemon has no art.'
